### ISSUE TITLE
Валидация

### ISSUE THREAD

**Issue by Morfey216** [vadimsmerekooo/peridona_SCIA#6]
Ошибок валидации быть не должно
http://joxi.ru/LmG1PXeIlRKb1A

**Comment by Morfey216** [comment]
И снова валидация: http://joxi.ru/DmBObWLs4wBMz2

**Comment by vadimsmerekooo** [comment]
Don't error valid
![image](https://user-images.githubusercontent.com/58609940/94953030-8fbaa200-04ef-11eb-8d1a-fa1c4c11b6b2.png)

**Comment by Morfey216** [comment]
Не, ну я тоже настойчивый парень...
Скажи, а посмотреть сброшенный мной скриншот не судьба? В нём нет ничего о языках.
Я даже не поленился сделать еще один: http://joxi.ru/4Ak4KBoTkyezzr
