### ISSUE TITLE
И снова Валидация

### ISSUE THREAD

**Issue by Morfey216** [vadimsmerekooo/peridona_SCIA#8]
Не, ну я тоже настойчивый парень...
Скажи, а посмотреть сброшенный мной скриншот не судьба? В нём нет ничего о языках.
Я даже не поленился сделать еще один: http://joxi.ru/4Ak4KBoTkyezzr

_Originally posted by @Morfey216 in https://github.com/vadimsmerekooo/peridona_SCIA/issues/6#issuecomment-702871664_

**Comment by vadimsmerekooo** [comment]
хаха
Согласен
Я у себя изменил, закомитить и запушить не успел 
поэтому, можно и закрыть issues, с вашего позволения

**Comment by Morfey216** [comment]
сначала запушь )))

**Comment by vadimsmerekooo** [comment]
пушнул

**Comment by vadimsmerekooo** [comment]
Fix validation 
don't error
